spring:
  application:
    name: springboot-study
  lifecycle:
    # 设置缓冲期，最大等待时间，默认：30秒
    timeout-per-shutdown-phase: 30s

# 健康监测
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

# 线程池
thread-pool:
  core-size: 5
  maximum-size: 10
  queue-capacity: 20
  keep-alive-seconds: 60


server:
  port: 8000
  ## 开启优雅停机，默认值：immediate 为立即关闭
  shutdown: graceful
